services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:3000"
    restart: unless-stopped
    networks:
      - default
      - host-server

networks:
  host-server:
    external: true
    name: host-server_default
